/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class', '[data-theme="dark"]'],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg)',
        surface: 'var(--surface)',
        'surface-2': 'var(--surface-2)',
        'surface-3': 'var(--surface-3)',
        border: 'var(--border)',
        'border-strong': 'var(--border-strong)',
        ink: 'var(--text)',
        'ink-muted': 'var(--text-muted)',
        'ink-faint': 'var(--text-faint)',
        terra: 'var(--accent)',
        'terra-hover': 'var(--accent-hover)',
        'terra-soft': 'var(--accent-soft)',
        'terra-ink': 'var(--accent-ink)',
        success: 'var(--success)',
        error: 'var(--error)',
        warning: 'var(--warning)',
        info: 'var(--info)',
        'st-learned': 'var(--st-learned)',
        'st-learning': 'var(--st-learning)',
        'st-weak': 'var(--st-weak)',
        'st-due': 'var(--st-due)',
        'st-new': 'var(--st-new)',
        'topic-grammar': 'var(--topic-grammar)',
        'topic-phonetics': 'var(--topic-phonetics)',
        'topic-lexicology': 'var(--topic-lexicology)',
        'topic-stylistics': 'var(--topic-stylistics)',
        background: 'var(--bg)',
        foreground: 'var(--text)',
        primary: 'var(--accent)',
        'primary-foreground': '#FDFBF5',
        card: 'var(--surface)',
        'card-foreground': 'var(--text)',
        popover: 'var(--surface)',
        'popover-foreground': 'var(--text)',
        secondary: 'var(--surface-2)',
        'secondary-foreground': 'var(--text)',
        muted: 'var(--surface-2)',
        'muted-foreground': 'var(--text-muted)',
        accent: 'var(--surface-2)',
        'accent-foreground': 'var(--text)',
        destructive: 'var(--error)',
        input: 'var(--border)',
        ring: 'var(--accent)',
      },
      fontFamily: {
        sans: ['Manrope', 'system-ui', 'sans-serif'],
        display: ['Spectral', 'Georgia', 'serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'flame-sway': {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
        'due-pulse': {
          '0%, 100%': { boxShadow: '0 0 0 0 var(--st-due-soft)' },
          '50%': { boxShadow: '0 0 0 6px transparent' },
        },
      },
      animation: {
        'flame-sway': 'flame-sway 2s ease-in-out infinite',
        'due-pulse': 'due-pulse 2.4s ease-in-out infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
